# Generated by Django 3.0.4 on 2020-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(choices=[('نقدي بالمدرسة', 'نقدي بالمدرسة'), ('1903530354880500015', '1903530354880500015'), ('1903530635939400011', '1903530635939400011'), ('1903530776181400019', '1903530776181400019'), ('1903530635939300017', '1903530635939300017'), ('1903530709961400015', '1903530709961400015')], max_length=19)),
                ('value', models.PositiveSmallIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('دراسية', 'دراسية'), ('باص', 'باص')], max_length=6)),
                ('school', models.CharField(blank=True, choices=[(None, ''), ('بنين', 'بنين'), ('بنات', 'بنات')], max_length=4)),
            ],
        ),
    ]
