# Generated by Django 3.0.4 on 2020-05-22 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(choices=[('مناره بنين', '1903530354880500000'), ('مناره بنات', '1903530635939400000'), ('IGCSE', '1903530776181400000'), ('سيارات', '1903530635939300000'), ('الفاروق', '1903530709961400000'), ('نقدي بالمدرسة', 'نقدي بالمدرسة')], max_length=16)),
                ('value', models.PositiveSmallIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('دراسية', 'دراسية'), ('باص', 'باص')], max_length=6)),
                ('school', models.CharField(blank=True, choices=[(None, ''), ('بنين', 'بنين'), ('بنات', 'بنات')], max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Living_area',
        ),
    ]
