# Generated by Django 3.0.4 on 2020-05-22 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0002_auto_20200522_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fees',
            new_name='Fee',
        ),
    ]
