# Generated by Django 3.0.4 on 2020-05-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20200522_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='bank_account',
            field=models.CharField(choices=[('1903530354880500015', '1903530354880500015'), ('1903530635939400011', '1903530635939400011'), ('1903530776181400019', '1903530776181400019'), ('1903530635939300017', '1903530635939300017'), ('1903530709961400015', '1903530709961400015'), ('نقدي بالمدرسة', 'نقدي بالمدرسة')], max_length=19),
        ),
    ]
