# Generated by Django 3.0.4 on 2020-06-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20200602_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='kind',
            field=models.CharField(choices=[('دراسية', 'دراسية'), ('سيارة', 'سيارة')], max_length=6),
        ),
    ]
