# Generated by Django 3.0.4 on 2020-05-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='message',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
