# Generated by Django 3.0.4 on 2020-05-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Living_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.Living_area'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Grade'),
        ),
    ]
