# Generated by Django 3.0.4 on 2020-05-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200524_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='study_fees',
            new_name='study_payment1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='study_payment',
            new_name='study_payment3',
        ),
    ]
