# Generated by Django 3.0.4 on 2020-05-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200527_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bus_payment',
            new_name='bus_payment2',
        ),
    ]
